providers = ["node", "python"]

[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

[phases.setup]
cmds = ["pip install -r backend/engine/requirements.txt"]

[phases.build]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend", 
  "npm run build --prefix frontend"
]

[phases.start]
cmd = "node backend/seed.js && npm start --prefix backend"
